"""modified course model

Revision ID: 78510060c709
Revises: 2efc711f3c0c
Create Date: 2023-10-07 14:03:15.430921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.courses.course import LikeState
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '78510060c709'
down_revision: Union[str, None] = '2efc711f3c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('likestate', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'likestate')
    # ### end Alembic commands ###
