"""cambios en la tabla courses x2

Revision ID: 991f1da78639
Revises: a40eccc1da70
Create Date: 2023-10-09 23:01:37.095712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991f1da78639'
down_revision: Union[str, None] = 'a40eccc1da70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
