"""model course

Revision ID: f014d0322258
Revises: da1bc5b5b7be
Create Date: 2023-10-05 21:15:39.743385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f014d0322258'
down_revision: Union[str, None] = 'da1bc5b5b7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_description'), 'courses', ['description'], unique=False)
    op.create_index(op.f('ix_courses_image'), 'courses', ['image'], unique=False)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_index(op.f('ix_courses_url'), 'courses', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_url'), table_name='courses')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index(op.f('ix_courses_image'), table_name='courses')
    op.drop_index(op.f('ix_courses_description'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
