"""revision

Revision ID: b9e2fac1de6b
Revises: 3c04345e00b8
Create Date: 2023-08-04 02:20:23.706503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e2fac1de6b'
down_revision = '3c04345e00b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('users_courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_courses',
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_course', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_course'], ['courses.id'], name='users_courses_id_course_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name='users_courses_id_user_fkey'),
    sa.PrimaryKeyConstraint('id_user', 'id_course', name='users_courses_pkey')
    )
    op.drop_table('user_course')
    # ### end Alembic commands ###
